name: Publish to NuGet

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Optionally, trigger for PRs to the main branch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache .NET SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.dotnet
            ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'  # Set your required .NET version
          
      - name: Authenticate with GitHub Packages
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name GitHubPackages --username ${{ github.actor }} --password ${{ secrets.NUGET_TOKEN }}
     
      - name: Find the highest version of the .nupkg file
        run: |
          highest_version=$(ls curl-static*.nupkg | sort -V | tail -n 1)
          echo "Highest version: $highest_version"
          echo "highest_version=$highest_version" >> $GITHUB_ENV  # Store the highest version in the environment variable

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push ${{ env.highest_version }} --api-key ${{ secrets.NUGET_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
