name: Publish to NuGet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
          
      #- name: Authenticate with GitHub Packages
      #  run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name GitHubPackages --username ${{ github.actor }} --password ${{ secrets.NUGET_TOKEN }}

      - name: Get the highest version of curl-static
        id: get_version
        run: |
          $nupkgFiles = Get-ChildItem -Path . -Filter "curl-static*.nupkg"
          
          $versionNumbers = $nupkgFiles | 
            ForEach-Object {
              if ($_.Name -match '(\d+\.\d+\.\d+)') {
                [version]$matches[1]
              }
            }

          $highestVersion = $versionNumbers | Sort-Object -Descending | Select-Object -First 1
         
          echo "::set-output name=VERSION::$highestVersion"
          
      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push curl-static.1.0.1.nupkg --source https://www.nuget.org/api/v2/package --apikey ${{ secrets.NUGET_TOKEN }}
